changelog:
  categories:
    - title: New Features
      labels:
        - "✨Feature"
    - title: Bug Fixes
      labels:
        - "🐛Bug"
    - title: Documentation
      labels:
        - "📖Doc"
    - title: Other Changes
      labels:
        - "*"
