//! 注入 / 持ち出しの匂いの検出語彙 (#1162)。UI 文言ではなく判定用のデータ。
//! 当たっても拒否ではなく「確認を強制」に使うので、誤検知は害にならない。
//! 日本語の語もここに置く (i18n-lint の対象外ファイル)。

pub const PATTERNS: &[&str] = &[
    "ignore previous",
    "ignore all previous",
    "ignore prior",
    "disregard",
    "system prompt",
    "you are now",
    "from now on",
    "always call",
    "always run",
    "always send",
    "never ask",
    "without confirm",
    "without asking",
    "api key",
    "api_key",
    "apikey",
    "token",
    "password",
    "secret",
    "http://",
    "https://",
    "curl ",
    "wget ",
    "base64",
    "<script",
    "指示を無視",
    "以前の指示",
    "確認なし",
    "確認せず",
    "常に実行",
    "必ず実行",
    "パスワード",
    "トークン",
];
