import { describe, expect, it } from 'vitest'
import { ALL_BUILTIN_CAPABILITIES } from './index'

describe('ALL_BUILTIN_CAPABILITIES', () => {
  it('exposes the expected built-in capability ids', () => {
    const ids = ALL_BUILTIN_CAPABILITIES.map((c) => c.id).sort()
    expect(ids).toEqual(
      [
        'account.current',
        'account.list',
        'ai.chat',
        'ai.listPersonas',
        'ai.sessions.list',
        'ai.sessions.read',
        'ai.sessions.search',
        'ai.setPersona',
        'aiscript.validate',
        'announcements.list',
        'antenna.list',
        'antenna.notes',
        'channel.list',
        'channel.notes',
        'chat.react',
        'chat.unreact',
        'clipboard.read',
        'clipboard.write',
        'clips.addNote',
        'clips.create',
        'clips.list',
        'clips.notes',
        'clips.removeNote',
        'column.active',
        'column.add',
        'column.focusedNote',
        'column.list',
        'column.move',
        'column.remove',
        'column.updateSettings',
        'drafts.create',
        'drafts.delete',
        'drafts.list',
        'drafts.update',
        'drive.list',
        'favorites.add',
        'favorites.remove',
        'federation.chart',
        'federation.instance',
        'federation.instances',
        'flash.list',
        'flash.show',
        'gallery.list',
        'http.fetch',
        'keybinds.list',
        'keybinds.reset',
        'keybinds.resetAll',
        'keybinds.set',
        'list.addUser',
        'list.list',
        'list.removeUser',
        'logs.recent',
        'memos.backlinks',
        'memos.create',
        'memos.delete',
        'memos.list',
        'memos.search',
        'memos.update',
        'meta.activeSkills',
        'meta.config',
        'meta.heartbeat',
        'meta.permissions',
        'meta.persona',
        'misstore.search',
        'navbar.list',
        'navbar.reset',
        'navbar.set',
        'notes.children',
        'notes.create',
        'notes.delete',
        'notes.pin',
        'notes.react',
        'notes.search',
        'notes.show',
        'notes.timeline',
        'notes.unpin',
        'notes.unreact',
        'notes.user',
        'notifications.list',
        'notifications.markRead',
        'pages.list',
        'pages.show',
        'performance.applySlider',
        'performance.list',
        'performance.reset',
        'performance.resetAll',
        'performance.set',
        'plugins.create',
        'plugins.delete',
        'plugins.history',
        'plugins.install',
        'plugins.list',
        'plugins.read',
        'plugins.revert',
        'plugins.setActive',
        'plugins.uninstall',
        'plugins.update',
        'registry.delete',
        'registry.get',
        'registry.listKeys',
        'registry.set',
        'role.notes',
        'skills.append',
        'skills.history',
        'skills.install',
        'skills.list',
        'skills.read',
        'skills.replaceSection',
        'skills.revert',
        'skills.toggle',
        'skills.uninstall',
        'styles.append',
        'styles.history',
        'styles.read',
        'styles.revert',
        'styles.write',
        'tasks.run',
        'theme.apply',
        'theme.create',
        'theme.history',
        'theme.install',
        'theme.list',
        'theme.read',
        'theme.revert',
        'theme.uninstall',
        'theme.update',
        'time.now',
        'ui.notify',
        'user.follow',
        'user.followers',
        'user.following',
        'user.lookup',
        'user.mute',
        'user.renoteMute',
        'user.search',
        'user.unfollow',
        'user.unmute',
        'user.unrenoteMute',
        'vault.fetch',
        'widgets.create',
        'widgets.delete',
        'widgets.history',
        'widgets.install',
        'widgets.list',
        'widgets.read',
        'widgets.revert',
        'widgets.setAutoRun',
        'widgets.uninstall',
        'widgets.update',
        'windows.close',
        'windows.closeAll',
        'windows.focus',
        'windows.list',
        'windows.open',
      ].sort(),
    )
  })

  it('every entry has a signature with a description', () => {
    // aiTool は capability ごとに true/false が選択される (例: ai.chat は false
    // で AI 本体からの自己再帰を防ぐ)。registry 登録の必須項目は signature。
    for (const cap of ALL_BUILTIN_CAPABILITIES) {
      expect(cap.signature, `${cap.id} signature`).toBeDefined()
      expect(typeof cap.signature?.description, `${cap.id} description`).toBe(
        'string',
      )
    }
  })

  it('every id uses dot-notation (Phase 1 命名規約)', () => {
    for (const cap of ALL_BUILTIN_CAPABILITIES) {
      // capability id は <subject>.<verb> ドット区切り。verb は単一語が
      // 推奨だが skills.replaceSection のように camelCase 複合語も許可。
      // 多段ネスト (例: ai.sessions.list) も許可。
      expect(cap.id, `${cap.id} should be dotted`).toMatch(
        /^[a-z]+(?:\.[a-zA-Z]+){1,2}$/,
      )
    }
  })
})
