import type { Command } from '@/commands/registry'
import { ACCOUNT_BUILTIN_CAPABILITIES } from './account'
import { AI_BUILTIN_CAPABILITIES } from './ai'
import { AI_SESSIONS_BUILTIN_CAPABILITIES } from './aiSessions'
import { AISCRIPT_BUILTIN_CAPABILITIES } from './aiscript'
import { ANNOUNCEMENTS_BUILTIN_CAPABILITIES } from './announcements'
import { ANTENNA_BUILTIN_CAPABILITIES } from './antenna'
import { CHANNEL_BUILTIN_CAPABILITIES } from './channel'
import { CHAT_BUILTIN_CAPABILITIES } from './chat'
import { CLIPBOARD_BUILTIN_CAPABILITIES } from './clipboard'
import { CLIPS_BUILTIN_CAPABILITIES } from './clips'
import { COLUMN_BUILTIN_CAPABILITIES } from './column'
import { DRAFTS_BUILTIN_CAPABILITIES } from './drafts'
import { DRIVE_BUILTIN_CAPABILITIES } from './drive'
import { FAVORITES_BUILTIN_CAPABILITIES } from './favorites'
import { FEDERATION_BUILTIN_CAPABILITIES } from './federation'
import { FLASH_BUILTIN_CAPABILITIES } from './flash'
import { GALLERY_BUILTIN_CAPABILITIES } from './gallery'
import { HTTP_BUILTIN_CAPABILITIES } from './http'
import { KEYBINDS_BUILTIN_CAPABILITIES } from './keybinds'
import { LIST_BUILTIN_CAPABILITIES } from './list'
import { LOGS_BUILTIN_CAPABILITIES } from './logs'
import { MEMOS_BUILTIN_CAPABILITIES } from './memos'
import { MEMOS_READ_BUILTIN_CAPABILITIES } from './memos-read'
import { META_BUILTIN_CAPABILITIES } from './meta'
import { MISSTORE_BUILTIN_CAPABILITIES } from './misstore'
import { NAVBAR_BUILTIN_CAPABILITIES } from './navbar'
import { NOTES_BUILTIN_CAPABILITIES } from './notes'
import { NOTES_WRITE_BUILTIN_CAPABILITIES } from './notes-write'
import { NOTIFICATIONS_BUILTIN_CAPABILITIES } from './notifications'
import { PAGES_BUILTIN_CAPABILITIES } from './pages'
import { PERFORMANCE_BUILTIN_CAPABILITIES } from './performance'
import { PERSONA_BUILTIN_CAPABILITIES } from './persona'
import { PLUGINS_BUILTIN_CAPABILITIES } from './plugins'
import { REGISTRY_BUILTIN_CAPABILITIES } from './registry'
import { ROLE_BUILTIN_CAPABILITIES } from './role'
import { SKILLS_BUILTIN_CAPABILITIES } from './skills'
import { STYLES_BUILTIN_CAPABILITIES } from './styles'
import { TASKS_BUILTIN_CAPABILITIES } from './tasks'
import { THEME_BUILTIN_CAPABILITIES } from './theme'
import { BUILTIN_CAPABILITIES as TIME_BUILTIN_CAPABILITIES } from './time'
import { UI_BUILTIN_CAPABILITIES } from './ui'
import { USER_BUILTIN_CAPABILITIES } from './user'
import { VAULT_BUILTIN_CAPABILITIES } from './vault'
import { WIDGETS_BUILTIN_CAPABILITIES } from './widgets'
import { WINDOWS_BUILTIN_CAPABILITIES } from './windows'

/**
 * NoteDeck に同梱されている AI tool として公開可能な capability の集合。
 * `main.ts` で起動時にこれらを `registerCapability` する。
 *
 * 命名規約: capability id はドット区切り (`<subject>.<verb>` 形式)。
 * Anthropic / OpenAI の tool name 制約に合わせて `toolSchema.ts` で
 * `_` に変換される (`time.now` → `time_now`)。
 */
export const ALL_BUILTIN_CAPABILITIES: readonly Command[] = [
  ...TIME_BUILTIN_CAPABILITIES,
  ...ACCOUNT_BUILTIN_CAPABILITIES,
  ...ANNOUNCEMENTS_BUILTIN_CAPABILITIES,
  ...ANTENNA_BUILTIN_CAPABILITIES,
  ...CHANNEL_BUILTIN_CAPABILITIES,
  ...COLUMN_BUILTIN_CAPABILITIES,
  ...THEME_BUILTIN_CAPABILITIES,
  ...STYLES_BUILTIN_CAPABILITIES,
  ...NAVBAR_BUILTIN_CAPABILITIES,
  ...NOTES_BUILTIN_CAPABILITIES,
  ...NOTES_WRITE_BUILTIN_CAPABILITIES,
  ...CLIPS_BUILTIN_CAPABILITIES,
  ...CHAT_BUILTIN_CAPABILITIES,
  ...DRAFTS_BUILTIN_CAPABILITIES,
  ...USER_BUILTIN_CAPABILITIES,
  ...NOTIFICATIONS_BUILTIN_CAPABILITIES,
  ...PAGES_BUILTIN_CAPABILITIES,
  ...DRIVE_BUILTIN_CAPABILITIES,
  ...FAVORITES_BUILTIN_CAPABILITIES,
  ...FEDERATION_BUILTIN_CAPABILITIES,
  ...FLASH_BUILTIN_CAPABILITIES,
  ...GALLERY_BUILTIN_CAPABILITIES,
  ...HTTP_BUILTIN_CAPABILITIES,
  ...KEYBINDS_BUILTIN_CAPABILITIES,
  ...LIST_BUILTIN_CAPABILITIES,
  ...MEMOS_BUILTIN_CAPABILITIES,
  ...MEMOS_READ_BUILTIN_CAPABILITIES,
  ...TASKS_BUILTIN_CAPABILITIES,
  ...UI_BUILTIN_CAPABILITIES,
  ...AI_BUILTIN_CAPABILITIES,
  ...AISCRIPT_BUILTIN_CAPABILITIES,
  ...PERSONA_BUILTIN_CAPABILITIES,
  ...SKILLS_BUILTIN_CAPABILITIES,
  ...WIDGETS_BUILTIN_CAPABILITIES,
  ...WINDOWS_BUILTIN_CAPABILITIES,
  ...PLUGINS_BUILTIN_CAPABILITIES,
  ...REGISTRY_BUILTIN_CAPABILITIES,
  ...ROLE_BUILTIN_CAPABILITIES,
  ...PERFORMANCE_BUILTIN_CAPABILITIES,
  ...CLIPBOARD_BUILTIN_CAPABILITIES,
  ...META_BUILTIN_CAPABILITIES,
  ...AI_SESSIONS_BUILTIN_CAPABILITIES,
  ...LOGS_BUILTIN_CAPABILITIES,
  ...MISSTORE_BUILTIN_CAPABILITIES,
  ...VAULT_BUILTIN_CAPABILITIES,
]
