// 生成物 — 手で編集しない。正本は crates/notecore/capabilities.json5 の permissions 節、
// 生成は `pnpm gen:capabilities`。意味 (preset / floor / deny の扱い) は schema.ts 側の
// コメントと #712 を参照 (#1133)。

export const PERMISSION_KEYS = [
  "notes.read",
  "notes.readArchive",
  "notes.write",
  "notes.react",
  "account.read",
  "account.write",
  "account.actAs",
  "drive.read",
  "drive.write",
  "memos.read",
  "memos.write",
  "clips.read",
  "clips.write",
  "drafts.read",
  "drafts.write",
  "network.external",
  "clipboard",
  "notifications",
  "tasks.run",
  "ai.invoke",
  "ai.persona.write",
  "skills.read",
  "skills.write",
  "theme.write",
  "styles.write",
  "navbar.write",
  "keybinds.write",
  "performance.write",
  "widgets.read",
  "widgets.write",
  "plugins.read",
  "plugins.write",
  "queries.read",
  "queries.write",
  "ai.sessions.read",
  "logs.read",
  "vault.use",
  "files.export",
  "backup.create",
  "deck.read",
  "deck.write",
] as const
export type PermissionKey = (typeof PERMISSION_KEYS)[number]

export const PERMISSION_PRESETS: Record<
  'readonly' | 'safe' | 'full',
  Record<PermissionKey, boolean>
> = {
  readonly: {
    "notes.read": true,
    "notes.readArchive": false,
    "notes.write": false,
    "notes.react": false,
    "account.read": true,
    "account.write": false,
    "account.actAs": false,
    "drive.read": true,
    "drive.write": false,
    "memos.read": true,
    "memos.write": false,
    "clips.read": true,
    "clips.write": false,
    "drafts.read": true,
    "drafts.write": false,
    "network.external": false,
    "clipboard": false,
    "notifications": false,
    "tasks.run": false,
    "ai.invoke": false,
    "ai.persona.write": false,
    "skills.read": true,
    "skills.write": false,
    "theme.write": false,
    "styles.write": false,
    "navbar.write": false,
    "keybinds.write": false,
    "performance.write": false,
    "widgets.read": true,
    "widgets.write": false,
    "plugins.read": true,
    "plugins.write": false,
    "queries.read": true,
    "queries.write": false,
    "ai.sessions.read": true,
    "logs.read": true,
    "vault.use": false,
    "files.export": false,
    "backup.create": false,
    "deck.read": true,
    "deck.write": false,
  },
  safe: {
    "notes.read": true,
    "notes.readArchive": false,
    "notes.write": false,
    "notes.react": true,
    "account.read": true,
    "account.write": false,
    "account.actAs": false,
    "drive.read": true,
    "drive.write": false,
    "memos.read": true,
    "memos.write": true,
    "clips.read": true,
    "clips.write": true,
    "drafts.read": true,
    "drafts.write": true,
    "network.external": false,
    "clipboard": true,
    "notifications": true,
    "tasks.run": true,
    "ai.invoke": true,
    "ai.persona.write": false,
    "skills.read": true,
    "skills.write": true,
    "theme.write": false,
    "styles.write": false,
    "navbar.write": false,
    "keybinds.write": false,
    "performance.write": false,
    "widgets.read": true,
    "widgets.write": true,
    "plugins.read": true,
    "plugins.write": true,
    "queries.read": true,
    "queries.write": true,
    "ai.sessions.read": true,
    "logs.read": true,
    "vault.use": false,
    "files.export": false,
    "backup.create": false,
    "deck.read": true,
    "deck.write": true,
  },
  full: {
    "notes.read": true,
    "notes.readArchive": true,
    "notes.write": true,
    "notes.react": true,
    "account.read": true,
    "account.write": true,
    "account.actAs": true,
    "drive.read": true,
    "drive.write": true,
    "memos.read": true,
    "memos.write": true,
    "clips.read": true,
    "clips.write": true,
    "drafts.read": true,
    "drafts.write": true,
    "network.external": true,
    "clipboard": true,
    "notifications": true,
    "tasks.run": true,
    "ai.invoke": true,
    "ai.persona.write": true,
    "skills.read": true,
    "skills.write": true,
    "theme.write": true,
    "styles.write": true,
    "navbar.write": true,
    "keybinds.write": true,
    "performance.write": true,
    "widgets.read": true,
    "widgets.write": true,
    "plugins.read": true,
    "plugins.write": true,
    "queries.read": true,
    "queries.write": true,
    "ai.sessions.read": true,
    "logs.read": true,
    "vault.use": true,
    "files.export": true,
    "backup.create": true,
    "deck.read": true,
    "deck.write": true,
  },
}

export const HIGH_RISK_PERMISSION_KEYS: readonly PermissionKey[] = [
  "notes.write",
  "account.write",
  "account.actAs",
  "drive.write",
  "memos.write",
  "network.external",
  "tasks.run",
  "ai.persona.write",
  "skills.write",
  "vault.use",
  "files.export",
  "backup.create",
]

export const AI_INSTRUCTION_KEYS: readonly PermissionKey[] = [
  "ai.persona.write",
  "skills.write",
]

export const THIRD_PARTY_DENY_KEYS: readonly PermissionKey[] = [
  "tasks.run",
  "ai.persona.write",
  "skills.write",
  "backup.create",
]

export const EXTERNAL_READ_FLOOR: readonly PermissionKey[] = [
  "notes.read",
  "account.read",
  "drive.read",
  "clips.read",
]

export const LOCAL_READ_KEYS: readonly PermissionKey[] = [
  "notes.readArchive",
  "memos.read",
  "drafts.read",
  "skills.read",
  "widgets.read",
  "plugins.read",
  "queries.read",
  "ai.sessions.read",
  "logs.read",
  "deck.read",
]
